# Generated by Django 4.0.3 on 2023-03-07 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='street_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='street_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='zip_code',
        ),
    ]
