# Generated by Django 4.0.3 on 2023-03-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_remove_customer_city_remove_customer_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
