# Generated by Django 4.0.3 on 2023-03-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0004_automobilevo_salerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salerecord',
            name='sales_price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
